config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  get 'students/add_student'
  post 'students/add_student'

  get 'students/show_student/:id', to: 'students#show_student', as: 'show_student'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
    self.per_page = 8
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def index
    @students = Student.all

    @students = Student.paginate(:page=>params[:page])
  end

  def add_student
    if request.post?
      @student = Student.new(set_params)
      if @student.save
        redirect_to show_student_url(@student)
      else
        render :action=> :add_student
      end
    end
  end

  def show_student
    @student = Student.find(params[:id])
  end

  private
  def set_params
    params.permit(:roll_no, :name, :maths, :physics, :chemistry)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImplManualMvc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/add_student.html.erb
<h1>Add Student</h1>
<%= form_with url:'/students/add_student', method: :post do |form| %>
    <div class = 'field'>
        <%= form.label :roll_no%>
        <%= form.number_field :roll_no %>
    </div>

    <div class = 'field'>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class = 'field'>
        <%= form.label :maths%>
        <%= form.number_field :maths %>
    </div>

    <div class = 'field'>
        <%= form.label :physics%>
        <%= form.number_field :physics %>
    </div>

    <div class = 'field'>
        <%= form.label :chemistry %>
        <%= form.number_field :chemistry %>
    </div>

    <div class="actions">
        <%= form.submit "Add Student"%>
    </div>

<% end %>

<%= link_to 'Back', '/students/index' %>

app/views/students/index.html.erb
<h1>Students Result</h1>

<table>
    <thead>
        <tr>
            <th>Roll No.</th>
            <th>Student Name</th>
            <th>Maths</th>
            <th>Physics</th>
            <th>Chemistry</th>
            <th>Total marks obtained</th>
            <th colspan=3>Action</th>
        </tr>
    </thead>

    <tbody>
        <% @students.each do |student| %>
            <tr>
                <td><%= student.roll_no %></td>
                <td><%= student.name %></td>
                <td><%= student.maths %></td>
                <td><%= student.physics %></td>
                <td><%= student.chemistry %></td>
                <td><%= student.maths.to_i + student.physics.to_i + student.chemistry.to_i %></td>
                <td><%= link_to 'Show Result', show_student_path(student)%>
            </tr>
        <% end %>
    </tbody>
</table>
<br>
<%= will_paginate @students %>
<br>
<%= link_to 'Add Student', '/students/add_student' %>

app/views/students/show_student.html.erb
<h1><%= @student.name %>'s Result</h1>

<p>
  <strong>Name:</strong>
  <%= @student.roll_no %>
</p>

<p>
  <strong>Maths:</strong>
  <%= @student.maths %>
</p>

<p>
  <strong>Physics:</strong>
  <%= @student.physics %>
</p>

<p>
  <strong>Chemistry:</strong>
  <%= @student.chemistry %>
</p>

<p>
  <strong>Total Marks Obtained:</strong>
  <% total_marks = @student.maths.to_i + @student.physics.to_i + @student.chemistry.to_i %>
  <%= total_marks %>
  <p>
  <strong>Result:</strong>
  <% if total_marks>=99 %>
  <%= "PASS" %>
  <% else %>
  <%= "FAIL" %>
  <% end %>
  <p>
</p>

<%= link_to 'Back', '/students/index' %>